// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeOps.Infrastructure.Persistence;

#nullable disable

namespace TradeOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeOpsDbContext))]
    [Migration("20260320062112_SeedDemoTenantsUsersCustomers")]
    partial class SeedDemoTenantsUsersCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeOps.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-5555-4555-8555-555555555505"),
                            Address = "Sydney NSW",
                            Name = "仅租户 A 可见的客户",
                            Phone = "0400000001",
                            TenantId = new Guid("a1111111-1111-4111-8111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-4666-8666-666666666606"),
                            Address = "Melbourne VIC",
                            Name = "仅租户 B 可见的客户",
                            Phone = "0400000002",
                            TenantId = new Guid("b2222222-2222-4222-8222-222222222202")
                        });
                });

            modelBuilder.Entity("TradeOps.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ABN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-4111-8111-111111111101"),
                            ABN = "11111111111",
                            BusinessName = "Acme Cleaning Pty Ltd",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-4222-8222-222222222202"),
                            ABN = "22222222222",
                            BusinessName = "Beta Maintenance Co",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TradeOps.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3333333-3333-4333-8333-333333333303"),
                            Email = "admin@acme.demo",
                            PasswordHash = "$2a$11$QySpUPrhdV9dQ5HEFA9dv..Ou2rlJLQQYNRVUpF3Pc//YqpRvT/IW",
                            Role = "Admin",
                            TenantId = new Guid("a1111111-1111-4111-8111-111111111101")
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-8444-444444444404"),
                            Email = "admin@beta.demo",
                            PasswordHash = "$2a$11$QySpUPrhdV9dQ5HEFA9dv..Ou2rlJLQQYNRVUpF3Pc//YqpRvT/IW",
                            Role = "Admin",
                            TenantId = new Guid("b2222222-2222-4222-8222-222222222202")
                        });
                });

            modelBuilder.Entity("TradeOps.Domain.Entities.Customer", b =>
                {
                    b.HasOne("TradeOps.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TradeOps.Domain.Entities.User", b =>
                {
                    b.HasOne("TradeOps.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TradeOps.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
